### PR TITLE
Added pop-os colour icon

### LINKED ISSUE #76: Pop! OS Icon Not Available
In the GRUB theme, the Pop! OS icon is not available instead it uses the default GNU/Linux icon. Would request an addition of the icon for the OS.

### PR DESCRIPTION
**Pull request by Dragon8oy**
- Added colour icon for Pop! OS, as the black and white version already exists.
 - Adjusted spacing for icons in logos.svg, to fit new icon, closes #76

### CODE REVIEW

**Comment by Dragon8oy** [comment]
It might be worth still merging this, as the colour and white versions of the pop os icon don't match after the latest commit to master.﻿

**Comment by vinceliuice** [comment]
There is conflicts, it can not be merged now!

**Comment by Dragon8oy** [comment]
If I sort the conflicts, will you merge?

**Comment by vinceliuice** [comment]
No problem!

**Comment by Dragon8oy** [comment]
I completely screwed up my fork and branch, so I created a new fork for it, and made the changes there. Closing this to avoid a duplicate merge request.

**Pull request closed without merging**
