### PR TITLE
Fix arguments being passed while authenticating

### PR DESCRIPTION
**Pull request by Dragon8oy**
## Changes:
 - If `tui_root_login` was used, not all arguments would be passed on during authentication, this is fixed by bringing it inline with the rest of the code

### CODE REVIEW

**Comment by vinceliuice** [comment]
It not working on dialog mode

**Comment by Dragon8oy** [comment]
Alright, let me take a look at it, I'll try and fix it then make a new request

**Comment by Dragon8oy** [comment]
I misinterpreted what the code was doing, with the old method it still fails when --custom-background is used, so I'll add a fix for it

**Comment by vinceliuice** [comment]
only add `--${theme} --${icon} --${screen}` is works well

**Comment by Dragon8oy** [comment]
Yes, but if --boot or --custom-background are used, then these won't have any effect if the wasn't called with root and uses dialog mode

**Comment by Dragon8oy** [comment]
Never mind, I misunderstood those code, again

**Comment by vinceliuice** [comment]
Yes! Dialog mode is only used for only run `./install.sh`

**Pull request merged**
