### PR TITLE
updated manjaro.png and added pop-os.png

### PR DESCRIPTION
**Pull request by mattiabiondi**

### CODE REVIEW

**Comment by mattiabiondi** [comment]
Pop!_OS switched to systemd-boot and `os-prober` uses `ubuntu` as `--class` for this distro.

**Comment by mattiabiondi** [comment]
Sorry, I've closed the pull request by accident

**Comment by mattiabiondi** [comment]
I confirm that modifying the `--class` parameter in `/boot/grub/grub.cfg` it works.

IMG_20190513_102622

**Comment by vinceliuice** [comment]
Thanks！

**Comment by Dean-Coakley** [comment]
@mattiabiondi For this to work I need to manually edit `/boot/grub/grub.cfg`

From
```
menuentry "Pop OS" --class ubuntu --class gnu-linux --class gnu --class os
```
to
```
menuentry "Pop OS" --class ubuntu --class gnu-linux --class gnu --class os --class popos
```

Is this correct?

**Comment by mattiabiondi** [comment]
@Dean-Coakley you have to substitute the first `--class` parameter `ubuntu` with `pop-os` like this: 
```
menuentry "Pop OS" --class pop-os --class gnu-linux --class gnu --class os
```

**Pull request merged**
