### PR TITLE
update icons: deepin, brunch-settings; fine tune icon parameters.

### PR DESCRIPTION
**Pull request by hotime**
1, update deepin icons to make the icon closer to the deepin logo, while also making the style suitable for this theme.
2, update brunch-settings icon for colors-white.svg, whitch has a different style effect from other icons of the colors-white style.
3, remove redundant element "g536" in group xubuntu for logos-whitesur.svg.
4, fine tune icon parameters like X,Y,width,height datas in SVG files, whitch has uncorrect datas. For example, all icon group in svg files are supposed to be 32.000x32.000, but a few icons are 32.001x32.001, and more...

[PNG file Changed List]
logos-color/    icons-1080p/deepin.png
                icons-2k/deepin.png
                icons-4k/deepin.png
logos-white/    icons-1080p/deepin.png, brunch-settings.png
                icons-2k/deepin.png, brunch-settings.png
                icons-4k/deepin.png, brunch-settings.png
logos-whitesur/ icons-1080p/deepin.png
                icons-2k/deepin.png
                icons-4k/deepin.png

[SVG file Changed List]
[logos-color.svg]
line1: deepin: remove path67, paste deepin.svg to this file, set 19x19, rename as path67, put it in group deepin.
line3: solus: h: 31.495->32.000
       steamos: w&h: 32.001->32.000
line5: void: w: 32.001->32.000
line8: brunch-settings: Y: 320.076->320.000
line9: driver: Y: 360.038->360.000
       edit: Y: 360.038->360.000
       efi: Y: 360.038->360.000
       find.efi: Y: 360.038->360.000

[logos-white.svg]
column5: all: X: 176.001-> 176.000
line1: all: Y: 16.001->16.000
       deepin: remove path60, paste deepin.svg to this file, set 19x19, rename as path60, put it in group deepin.
line2: all: Y: 56.001->56.000
line3: all: Y: 96.001->96.000
       solus: h: 32.001->32.000
       steamos: w&h: 32.001->32.000
line4: all: Y: 136.001->136.000
line5: all: Y: 176.00*->176.000
       void: w&h: 32.001->32.000
line6: all: Y: 216.001->216.000
       4MLinux & AlpineLinux: w&h: 32.001->32.000
line7: all: Y: 256.001->256.000
       freebsd: w&h: 32.001->32.000
       brunch: X: 256.001->256.000
line8: all: Y: 320.\*\*\*->320.000
       brunch-settings: paste path1502 from logos-color.svg to logos-white.svg, put it in group brunch-settings, set path1500's opacity from 100% to 0%
line9: all: Y: 360.\*\*\*->360.000
line10:all: Y: 400.001->400.000

[colors-whitesur.svg]
column6: all: X: 217.482-> 216.000
all lines: all: h: 31.999->32.000
line1: deepin: X: 217.482->216.000, remove path330, paste deepin.svg to this file, set 19x19, rename as path330, put it in group deepin.
line2: all: Y: 56.994->56.000
       xubuntu: remove Redundant g536, X: 218.963->216.000
line8: submenu & brunch-settings: Y: 320.857->320.000
line9: all: Y: 360.***->360.000

### CODE REVIEW

**Comment by hotime** [comment]
Something went wrong. I opened logos-color.svg using Adobe AI but lost some icons, trying to figure out...

**Comment by hotime** [comment]
PS：才刚注意到仓库主人也来自中国，早点留意到的话就不用翻译了... 0.0

1、更新所有主题中的"deepin"图标，使其更接近deepin官方logo，同时仍然保持图标与其相应主题的风格不变。

2、更新colors-white主题中的"brunch settings"图标，因为它目前显示的大图标与同主题中的其他图标的风格差异过大（主要是体型上的）。

3、删除whitesur主题中 xubuntu图标中设计之外的的冗余元素“g536”，其导致该svg文件中xubuntu的图标组范围与预期不符。

4、微调SVG文件中部分图标存在的 X、Y、宽度、高度 数据不统一的问题。例如，svg文件中的所有图标组都应该是32.000x32.000，但一些图标是32.001x32.001，其他详细改变详见下述内容：


[PNG图标 修改列表]
logos-color/    icons-1080p/deepin.png
                icons-2k/deepin.png
                icons-4k/deepin.png
logos-white/    icons-1080p/deepin.png, brunch-settings.png
                icons-2k/deepin.png, brunch-settings.png
                icons-4k/deepin.png, brunch-settings.png
logos-whitesur/ icons-1080p/deepin.png
                icons-2k/deepin.png
                icons-4k/deepin.png


[SVG文件 修改列表]
[logos-color.svg]
行1: deepin: 移除path67, 粘贴deepin.svg至当前文件, 大小设为19x19, 重命名为 path67, 置于deepin组中.
行3: solus: h: 31.495->32.000
       steamos: w&h: 32.001->32.000
行5: void: w: 32.001->32.000
行8: brunch-settings: Y: 320.076->320.000
行9: driver: Y: 360.038->360.000
       edit: Y: 360.038->360.000
       efi: Y: 360.038->360.000
       find.efi: Y: 360.038->360.000

[logos-white.svg]
列5: 所有图标: X: 176.001-> 176.000
行1: 所有图标: Y: 16.001->16.000
       deepin: 移除path60, 粘贴deepin.svg至当前文件, 大小设为19x19, 重命名为 path60, 置于deepin组中.
行2: 所有图标: Y: 56.001->56.000
行3: 所有图标: Y: 96.001->96.000
       solus: h: 32.001->32.000
       steamos: w&h: 32.001->32.000
行4: 所有图标: Y: 136.001->136.000
行5: 所有图标: Y: 176.00*->176.000
       void: w&h: 32.001->32.000
行6: 所有图标: Y: 216.001->216.000
       4MLinux & AlpineLinux: w&h: 32.001->32.000
行7: 所有图标: Y: 256.001->256.000
       freebsd: w&h: 32.001->32.000
       brunch: X: 256.001->256.000
行8: 所有图标: Y: 320.\*\*\*->320.000
       brunch-settings: 从logos-color.svg中复制path1502至logos-white.svg, 置于brunch-settings组中, 将path1500的不透明度由100%修改为0%
行9: 所有图标: Y: 360.\*\*\*->360.000
行10:所有图标: Y: 400.001->400.000

[colors-whitesur.svg]
列6: 所有图标: X: 217.482-> 216.000
所有行: 所有图标: h: 31.999->32.000
行1: deepin: X: 217.482->216.000, 移除path330, 粘贴deepin.svg至当前文件, 大小设为19x19, 重命名为 path330, 置于deepin组中.
行2: 所有图标: Y: 56.994->56.000
       xubuntu: 移除多余的g536, X: 218.963->216.000
行8: submenu & brunch-settings: Y: 320.857->320.000
行9: 所有图标: Y: 360.***->360.000

**Comment by hotime** [comment]
终于整理完了，辛苦库主审核了哈。有什么问题的话请随时留言，我再去修改。

**Comment by vinceliuice** [comment]
要得

**Pull request merged**
