### PR TITLE
Updated elementary OS & added Parrot OS icons

### PR DESCRIPTION
**Pull request by joe733**
### Coloured

| OS | 1080p | 2k | 4k |
| --- | --- | --- | --- |
| elementary OS | ![][1] | ![][2] | ![][3] |
| Parrot OS | ![][4] | ![][5] | ![][6] |

[1]: https://user-images.githubusercontent.com/38415384/85004659-70347f00-b175-11ea-8942-c0d1079a13e4.png
[2]: https://user-images.githubusercontent.com/38415384/85008170-387c0600-b17a-11ea-9bcd-e318abf23d9e.png
[3]: https://user-images.githubusercontent.com/38415384/85008288-66614a80-b17a-11ea-8f1e-a89305ee6668.png
[4]: https://user-images.githubusercontent.com/38415384/85008599-cfe15900-b17a-11ea-8c70-3a1c976d4f7e.png
[5]: https://user-images.githubusercontent.com/38415384/85008421-9b6d9d00-b17a-11ea-9ecf-e63b50f20a5a.png
[6]: https://user-images.githubusercontent.com/38415384/85008513-b809d500-b17a-11ea-86cf-948e4f626665.png

| OS | 1080p | 2k | 4k |
| --- | --- | --- | --- |
| Parrot OS | ![][7] | ![][8] | ![][9] |

[7]: https://user-images.githubusercontent.com/38415384/85008869-31092c80-b17b-11ea-8fa4-8f6b18db194d.png
[8]: https://user-images.githubusercontent.com/38415384/85008977-5a29bd00-b17b-11ea-8a08-d2166f11d1d5.png
[9]: https://user-images.githubusercontent.com/38415384/85008916-41b9a280-b17b-11ea-996a-27104f64a360.png

### CODE REVIEW

**Comment by joe733** [comment]
@vinceliuice thanks for merging my pull.

May I ask a few questions.

1. That white icons for Parrot OS is okay... right, does it not blend with the background for Vimix, Stylish and Slaze?
2. I'm having trouble adding an icon for a custom boot menu entry. Can you help me [here](https://unix.stackexchange.com/questions/593562/how-to-add-icon-to-a-custom-grub-boots-script)?

**Comment by vinceliuice** [comment]
This is beyond my knowledge and I also don’t know how to deal with it

**Comment by joe733** [comment]
Oh and one more thing, I use an `image-bot` which automatically compresses images. Here's the pull request on my fork: https://github.com/joe733/grub2-themes/pull/1, you might wanna check it out before I merge it to master and create a pull here.

**Comment by vinceliuice** [comment]
OK!

**Pull request merged**
